/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

/**
 *
 * @author angel
 */
public class NewMainFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewMainFrame
     */
    public NewMainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        Simulacion = new javax.swing.JPanel();
        ControlsPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        policySelector = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        RRQuantumSpinner = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        level0Spinner = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        level1Spinner = new javax.swing.JSpinner();
        jLabel7 = new javax.swing.JLabel();
        level2Spinner = new javax.swing.JSpinner();
        jLabel8 = new javax.swing.JLabel();
        level3Spinner = new javax.swing.JSpinner();
        jLabel9 = new javax.swing.JLabel();
        speedSlider = new javax.swing.JSlider();
        msLabel = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        maxMemorySpinner = new javax.swing.JSpinner();
        pauseBtn = new javax.swing.JButton();
        StartBtn = new javax.swing.JButton();
        restartBtn = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        processNameField = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        arrivalSpinner = new javax.swing.JSpinner();
        jLabel15 = new javax.swing.JLabel();
        instructionSpinner = new javax.swing.JSpinner();
        jLabel16 = new javax.swing.JLabel();
        ioCycleSpinner = new javax.swing.JSpinner();
        createProcessBtn = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        processType = new javax.swing.JComboBox<>();
        ioDurationSpinner = new javax.swing.JSpinner();
        Create20ProcessBtn = new javax.swing.JButton();
        CpuPanel = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        QueuesPanel = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTextField2 = new javax.swing.JTextField();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTextField3 = new javax.swing.JTextField();
        jScrollPane9 = new javax.swing.JScrollPane();
        jTextField4 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        saveFile = new javax.swing.JButton();
        loadFile = new javax.swing.JButton();
        Logs = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        Charts = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Simulacion.setBackground(new java.awt.Color(53, 73, 133));
        Simulacion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ControlsPanel.setBackground(new java.awt.Color(53, 73, 133));
        ControlsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Controles", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        ControlsPanel.setForeground(new java.awt.Color(255, 255, 255));
        ControlsPanel.setOpaque(false);
        ControlsPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Simulador de CPU");
        ControlsPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Planificador:");
        ControlsPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 110, 20));

        policySelector.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        ControlsPanel.add(policySelector, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 690, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Quantum:");
        ControlsPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 50, 60, 20));
        ControlsPanel.add(RRQuantumSpinner, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 50, 60, -1));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Feedback:");
        ControlsPanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Nivel 0:");
        ControlsPanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 60, 20));
        ControlsPanel.add(level0Spinner, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 60, -1));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Nivel 1:");
        ControlsPanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, 60, 20));
        ControlsPanel.add(level1Spinner, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, 60, -1));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Nivel 2:");
        ControlsPanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 80, 60, 20));
        ControlsPanel.add(level2Spinner, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 80, 60, -1));

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Nivel 3:");
        ControlsPanel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 80, 60, 20));
        ControlsPanel.add(level3Spinner, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 80, 60, -1));

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Velocidad (ms):");
        ControlsPanel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 90, 20));
        ControlsPanel.add(speedSlider, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 670, -1));

        msLabel.setForeground(new java.awt.Color(255, 255, 255));
        msLabel.setText("-- ms");
        ControlsPanel.add(msLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 110, 50, 20));

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Procesos en memoria:");
        ControlsPanel.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));
        ControlsPanel.add(maxMemorySpinner, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, -1, -1));

        pauseBtn.setText("Pausar");
        pauseBtn.setPreferredSize(new java.awt.Dimension(73, 23));
        ControlsPanel.add(pauseBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 180, -1, -1));

        StartBtn.setText("Iniciar");
        StartBtn.setPreferredSize(new java.awt.Dimension(73, 23));
        ControlsPanel.add(StartBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, -1, -1));

        restartBtn.setText("Reiniciar");
        restartBtn.setMaximumSize(new java.awt.Dimension(72, 23));
        restartBtn.setMinimumSize(new java.awt.Dimension(72, 23));
        restartBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restartBtnActionPerformed(evt);
            }
        });
        ControlsPanel.add(restartBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 180, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Crear Proceso");
        ControlsPanel.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 130, 30));

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Nombre:");
        ControlsPanel.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 50, 20));
        ControlsPanel.add(processNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, 490, -1));

        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Arribo (ciclo):");
        ControlsPanel.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 90, 20));
        ControlsPanel.add(arrivalSpinner, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, 80, -1));

        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Instrucciones:");
        ControlsPanel.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 270, 100, 20));
        ControlsPanel.add(instructionSpinner, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 270, 80, -1));

        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Ciclo I/O:");
        ControlsPanel.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 270, 70, 20));
        ControlsPanel.add(ioCycleSpinner, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 270, 90, -1));

        createProcessBtn.setText("Crear Proceso");
        createProcessBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createProcessBtnActionPerformed(evt);
            }
        });
        ControlsPanel.add(createProcessBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 140, -1));

        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Tipo:");
        ControlsPanel.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 270, 80, 20));

        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Duracion I/O:");
        ControlsPanel.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 300, 80, 20));

        processType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        ControlsPanel.add(processType, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 270, 130, -1));
        ControlsPanel.add(ioDurationSpinner, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 300, 130, -1));

        Create20ProcessBtn.setText("Crear 20 Procesos");
        ControlsPanel.add(Create20ProcessBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 310, -1, -1));

        Simulacion.add(ControlsPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1030, 350));

        CpuPanel.setBackground(new java.awt.Color(53, 73, 133));
        CpuPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "CPU", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        CpuPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Proceso:");
        CpuPanel.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("ID:");
        CpuPanel.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("PC:");
        CpuPanel.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("MAR:");
        CpuPanel.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Total:");
        CpuPanel.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Ciclo actual:");
        CpuPanel.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Modo:");
        CpuPanel.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("0");
        CpuPanel.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 60, -1));

        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("OS");
        CpuPanel.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, 60, -1));

        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("--");
        CpuPanel.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 60, -1));

        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("--");
        CpuPanel.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 60, -1));

        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("--");
        CpuPanel.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 60, -1));

        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText("--");
        CpuPanel.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 60, -1));

        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("N/A");
        CpuPanel.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 60, -1));

        Simulacion.add(CpuPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 370, 180, 240));

        QueuesPanel.setBackground(new java.awt.Color(53, 73, 133));
        QueuesPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Colas de Procesos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        QueuesPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel33.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel33.setText("Listos");
        QueuesPanel.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 110, -1));

        jLabel34.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel34.setText("Suspendidos");
        QueuesPanel.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 30, 110, -1));

        jLabel35.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(255, 255, 255));
        jLabel35.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel35.setText("Terminados");
        QueuesPanel.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, 110, -1));

        jLabel36.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(255, 255, 255));
        jLabel36.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel36.setText("Bloqueados");
        QueuesPanel.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 110, -1));

        jTextField1.setText("jTextField1");
        jScrollPane6.setViewportView(jTextField1);

        QueuesPanel.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 100, 160));

        jTextField2.setText("jTextField2");
        jScrollPane7.setViewportView(jTextField2);

        QueuesPanel.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 100, 160));

        jTextField3.setText("jTextField3");
        jScrollPane8.setViewportView(jTextField3);

        QueuesPanel.add(jScrollPane8, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, 100, 160));

        jTextField4.setText("jTextField4");
        jScrollPane9.setViewportView(jTextField4);

        QueuesPanel.add(jScrollPane9, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 60, 100, 160));

        Simulacion.add(QueuesPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 500, 230));

        jPanel1.setBackground(new java.awt.Color(53, 73, 133));

        saveFile.setText("Guardar");

        loadFile.setText("Cargar");
        loadFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadFileActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(saveFile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(loadFile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(126, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(saveFile)
                .addGap(48, 48, 48)
                .addComponent(loadFile)
                .addContainerGap(74, Short.MAX_VALUE))
        );

        Simulacion.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 380, 310, 220));

        jTabbedPane1.addTab("Simulacion", Simulacion);

        Logs.setBackground(new java.awt.Color(53, 73, 133));
        Logs.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane5.setViewportView(jTextArea1);

        Logs.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 990, 560));

        jTabbedPane1.addTab("Configuracion", Logs);

        Charts.setBackground(new java.awt.Color(53, 73, 133));
        Charts.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jTabbedPane1.addTab("Graficos", Charts);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void createProcessBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createProcessBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_createProcessBtnActionPerformed

    private void restartBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restartBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_restartBtnActionPerformed

    private void loadFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadFileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loadFileActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewMainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Charts;
    private javax.swing.JPanel ControlsPanel;
    private javax.swing.JPanel CpuPanel;
    private javax.swing.JButton Create20ProcessBtn;
    private javax.swing.JPanel Logs;
    private javax.swing.JPanel QueuesPanel;
    private javax.swing.JSpinner RRQuantumSpinner;
    private javax.swing.JPanel Simulacion;
    private javax.swing.JButton StartBtn;
    private javax.swing.JSpinner arrivalSpinner;
    private javax.swing.JButton createProcessBtn;
    private javax.swing.JSpinner instructionSpinner;
    private javax.swing.JSpinner ioCycleSpinner;
    private javax.swing.JSpinner ioDurationSpinner;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JSpinner level0Spinner;
    private javax.swing.JSpinner level1Spinner;
    private javax.swing.JSpinner level2Spinner;
    private javax.swing.JSpinner level3Spinner;
    private javax.swing.JButton loadFile;
    private javax.swing.JSpinner maxMemorySpinner;
    private javax.swing.JLabel msLabel;
    private javax.swing.JButton pauseBtn;
    private javax.swing.JComboBox<String> policySelector;
    private javax.swing.JTextField processNameField;
    private javax.swing.JComboBox<String> processType;
    private javax.swing.JButton restartBtn;
    private javax.swing.JButton saveFile;
    private javax.swing.JSlider speedSlider;
    // End of variables declaration//GEN-END:variables
}
